name: PETALA
favicon: null
layout_spectrum: 0.91969
typography_spectrum: 0.40887
title: PETALA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101727'
    - '#265d7b'
    - '#fed9ad'
    - '#ee4957'
    - '#fe9264'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
